server:
  port: 9000

spring:
  application:
    name: spring3-jpa

  jpa:
    database-platform: org.hibernate.community.dialect.MariaDBLegacyDialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        show_sql: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:13306/yjlove82?characterEncoding=UTF-8&serverTimezone=UTC
    username: yjlove82
    password: love1234
